version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: yuem-tang
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    restart: always

  app:
    build: .
    container_name: yuem-tang-app
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: user
      DATABASE_PASSWORD: test1234
      DATABASE_NAME: yuem-tang
      JWT_SECRET: v56rA7iigy5oTRp4aSEig6skdkQZYlX9
    ports:
      - '3000:3000'
    depends_on:
      - db
    restart: always

volumes:
  postgres-data:
